# Air configuration for hot-reloading in development
# https://github.com/air-verse/air

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "tmp/main"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor", "tests"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
